version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npm start

  test:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test
    environment:
      - CI=true

  storybook:
    build: .
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run storybook
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
